#!/usr/bin/env bash
# test-skill.sh — Regression suite for the single-branch-development hooks bundle.
#
# Tests: track-preflight, track-reconcile, track-guard, track-evidence (producer),
#        track-evidence-gate, track-meter, track-trace, track-sentinel, track-notify,
#        structural integrity. Includes a producer->gate end-to-end contract so the
#        evidence record is generated by track-evidence.sh, never hand-written.
#        11 suites · 66 total · 65 passed · 0 failed · 1 skipped (2026-07-04)
#
# Usage:
#   bash .github/skills/single-branch-development/tests/test-skill.sh
#   bash tests/test-skill.sh          # from inside single-branch-development/ dir
#
# Requirements: bash, jq, git (gh auth bypassed via PREFLIGHT_REQUIRE_GH=0).
# Side-effects: temp branch + temp runs/ dir; cleaned up on exit.
# Exit: 0 = all passed, 1 = one or more failures.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$SCRIPT_DIR/../scripts"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT"

GUARD="$SCRIPTS_DIR/track-guard.sh"
PREFLIGHT="$SCRIPTS_DIR/track-preflight.sh"
RECONCILE="$SCRIPTS_DIR/track-reconcile.sh"
EVIDENCE="$SCRIPTS_DIR/track-evidence.sh"
EVIDENCE_GATE="$SCRIPTS_DIR/track-evidence-gate.sh"
METER="$SCRIPTS_DIR/track-meter.sh"
TRACE="$SCRIPTS_DIR/track-trace.sh"
SENTINEL="$SCRIPTS_DIR/track-sentinel.sh"
NOTIFY="$SCRIPTS_DIR/track-notify.sh"
for s in "$GUARD" "$PREFLIGHT" "$RECONCILE" "$EVIDENCE" "$EVIDENCE_GATE" \
         "$METER" "$TRACE" "$SENTINEL" "$NOTIFY"; do
  [ -x "$s" ] || chmod +x "$s"
done

# ---------------------------------------------------------------------------
# Harness
# ---------------------------------------------------------------------------
PASS=0; FAIL=0; SKIP=0; FAILURES=""
pass() { PASS=$((PASS+1)); printf '  OK    %s\n' "$1"; }
fail() { FAIL=$((FAIL+1)); printf '  FAIL  %s\n' "$1"; FAILURES="$FAILURES\n  - $1"; }
skip() { SKIP=$((SKIP+1)); printf '  SKIP  %s\n' "$1"; }
section() { printf '\n--- %s ---\n' "$1"; }

assert_deny() {
  local desc="$1" hook="$2" json="$3"; shift 3
  local result
  result=$(printf '%s' "$json" | env "$@" bash "$hook" 2>&1) || true
  if printf '%s' "$result" | grep -qE '"deny"|"block"'; then pass "$desc"
  else fail "$desc (got: $(printf '%s' "$result" | head -c 120))"; fi
}
assert_allow() {
  local desc="$1" hook="$2" json="$3"; shift 3
  local result
  result=$(printf '%s' "$json" | env "$@" bash "$hook" 2>&1) || true
  if printf '%s' "$result" | grep -qE '"deny"|"block"'; then
    fail "$desc (expected allow, got: $(printf '%s' "$result" | head -c 120))"
  else pass "$desc"; fi
}

# ---------------------------------------------------------------------------
# Temp state
# ---------------------------------------------------------------------------
TMPDIR_RUNS="$(mktemp -d)"
ORIG_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)"
TEST_BRANCH="test/sbd-skill-$(date +%s)"
SCRATCH_FILES=()
RUN1_ID=""

cleanup() {
  git checkout "$ORIG_BRANCH" --quiet 2>/dev/null || true
  git branch -D "$TEST_BRANCH" --quiet 2>/dev/null || true
  for f in "${SCRATCH_FILES[@]:-}"; do
    git rm --cached "$f" --quiet 2>/dev/null || true; rm -f "$f"; done
  rm -rf "$TMPDIR_RUNS"
}
trap cleanup EXIT
git checkout -b "$TEST_BRANCH" --quiet 2>/dev/null

# Fingerprint matching evidence-gate/evidence exactly (HEAD + diff + untracked)
current_fingerprint() {
  local hc; command -v shasum >/dev/null 2>&1 && hc=shasum || hc=sha1sum
  { git rev-parse HEAD 2>/dev/null || echo no-head
    git diff HEAD 2>/dev/null || true
    local u; u="$(git ls-files --others --exclude-standard 2>/dev/null || true)"
    if [ -n "$u" ]; then
      printf '%s\n' "$u"; printf '%s\n' "$u" | git hash-object --stdin-paths 2>/dev/null || true
    fi
  } | $hc | cut -d' ' -f1
}

ABS="${REPO_ROOT}/"

# ---------------------------------------------------------------------------
# SUITE 1 -- track-preflight.sh
# ---------------------------------------------------------------------------
section "track-preflight.sh"

result=$(TRACK_ID=tst-setup TASKS="T001-T005" TRACK_BASE_REF=main \
         PREFLIGHT_REQUIRE_GH=0 RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
if printf '%s' "$result" | grep -q '"mode":"start"'; then
  pass "preflight: fresh start -> mode=start + RUN_ID minted"
  RUN1_ID=$(printf '%s' "$result" | grep -o '"run_id":"[^"]*"' | cut -d'"' -f4)
else fail "preflight: fresh start -> mode=start + RUN_ID minted"; fi

TRACK_ID=tst-setup TASKS="T001-T005" TRACK_BASE_REF=main \
PREFLIGHT_REQUIRE_GH=0 RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" --commit >/dev/null 2>&1
ls "$TMPDIR_RUNS"/*.dispatch >/dev/null 2>&1 \
  && pass "preflight: --commit persists .dispatch breadcrumb" \
  || fail "preflight: --commit persists .dispatch breadcrumb"

result=$(TRACK_ID=tst-setup TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
         RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
printf '%s' "$result" | grep -q '"mode":"resume"' \
  && pass "preflight: same slug -> RESUME mode" || fail "preflight: same slug -> RESUME mode"

result2=$(TRACK_ID=tst-other TRACK_BASE_REF=main PREFLIGHT_REQUIRE_GH=0 \
          RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>&1)
printf '%s' "$result2" | grep -q '"mode":"start"' \
  && pass "preflight: different slug -> fresh START" \
  || fail "preflight: different slug -> fresh START"

RUNS_DIR="$TMPDIR_RUNS" bash "$PREFLIGHT" 2>/dev/null \
  && fail "preflight: missing TRACK_ID -> hard-fail exit 1" \
  || pass "preflight: missing TRACK_ID -> hard-fail exit 1"

# ---------------------------------------------------------------------------
# SUITE 2 -- track-reconcile.sh
# ---------------------------------------------------------------------------
section "track-reconcile.sh"

if [ -n "$RUN1_ID" ]; then
  printf '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":"0000000000000000000000000000000000000001"}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" TRACK_BASE_REF=main \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$RECONCILE" 2>/dev/null)
  printf '%s' "$result" | jq -e '.evidence.stale | index("go-test") != null' >/dev/null 2>&1 \
    && pass "reconcile: stale evidence identified" \
    || fail "reconcile: stale evidence identified"

  result=$(printf '{}' | TRACK_ID=tst-setup RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_BASE_REF=main bash "$RECONCILE" 2>/dev/null)
  printf '%s' "$result" | jq -e '.run_id != null' >/dev/null 2>&1 \
    && pass "reconcile: RUN_ID auto-recovered from breadcrumb" \
    || fail "reconcile: RUN_ID auto-recovered from breadcrumb"

  RECON_FP=$(printf '{}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
             TRACK_BASE_REF=main bash "$RECONCILE" 2>/dev/null | jq -r '.fingerprint')
  GATE_FP=$(current_fingerprint)
  [ "$RECON_FP" = "$GATE_FP" ] \
    && pass "reconcile: fingerprint == evidence-gate (bug-regression)" \
    || fail "reconcile: fingerprint mismatch (reconcile=$RECON_FP gate=$GATE_FP)"
else
  skip "reconcile: stale evidence (no RUN1_ID)"; skip "reconcile: auto-recovery (no RUN1_ID)"
  skip "reconcile: fingerprint parity (no RUN1_ID)"
fi

EMPTY_RUNS="$(mktemp -d)"
result=$(printf '{}' | RUNS_DIR="$EMPTY_RUNS" bash "$RECONCILE" 2>/dev/null)
[ -z "$result" ] && pass "reconcile: no breadcrumb -> silent no-op" \
  || fail "reconcile: no breadcrumb -> silent no-op"
rm -rf "$EMPTY_RUNS"

# ---------------------------------------------------------------------------
# SUITE 3 -- track-guard.sh (file edits)
# ---------------------------------------------------------------------------
section "track-guard.sh -- file ownership"

assert_allow "guard: path within allowed prefix -> allow" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-go/postgres.go\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/:frontend/"

assert_deny "guard: path outside allowed prefix -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-python/main.py\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/:frontend/"

assert_deny "guard: frozen entrypoint -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"${ABS}backend-go/cmd/api/main.go\"}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" \
  "TRACK_FROZEN_PATHS=backend-go/cmd/api/main.go"

TMP_GEN="$(mktemp "${REPO_ROOT}/sbd_tgen_XXXXXX.go")"
printf '// GENERATED \xe2\x80\x94 DO NOT EDIT\n// auto-generated\npackage main\n' > "$TMP_GEN"
result=$(printf '%s' \
  "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"$TMP_GEN\"}}" \
  | TRACK_ALLOWED_PREFIXES="sbd_tgen_" bash "$GUARD" 2>&1) || true
rm -f "$TMP_GEN"
printf '%s' "$result" | grep -q '"deny"' \
  && pass "guard: GENERATED banner -> deny" || fail "guard: GENERATED banner -> deny"

REAL_COM=".github/instructions/go.instructions.md"
if git log --oneline -1 -- "$REAL_COM" 2>/dev/null | grep -q .; then
  assert_deny "guard: committed file under immutable prefix -> deny" \
    "$GUARD" \
    "{\"tool_name\":\"replace_string_in_file\",\"tool_input\":{\"filePath\":\"${ABS}${REAL_COM}\"}}" \
    "TRACK_ALLOWED_PREFIXES=.github/" \
    "TRACK_IMMUTABLE_PREFIXES=.github/instructions/"
else skip "guard: immutable prefix (file not committed)"; fi

assert_deny "guard: multi_replace with one out-of-scope path -> deny" \
  "$GUARD" \
  "{\"tool_name\":\"multi_replace_string_in_file\",\"tool_input\":{\"replacements\":[{\"filePath\":\"${ABS}backend-go/kernel/auth.go\"},{\"filePath\":\"${ABS}backend-python/main.py\"}]}}" \
  "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: unset TRACK_ALLOWED_PREFIXES -> fail-closed deny" \
  "$GUARD" \
  "{\"tool_name\":\"create_file\",\"tool_input\":{\"filePath\":\"${ABS}anything/test.py\"}}"

# ---------------------------------------------------------------------------
# SUITE 4 -- track-guard.sh (terminal lockout)
# ---------------------------------------------------------------------------
section "track-guard.sh -- terminal lockout"

# Test commands are injected at build time; see note at top of script.
T_PUSH_CMD="git push origin branch"
T_FPUSH_CMD="git push --force origin branch"
T_PRMERGE_CMD="gh pr merge 42 --merge"
T_RESETHARD_CMD="git reset --hard HEAD~1"
T_FFPUSH_CMD="git push origin mybranch"
T_DROP_CMD='DROP TABLE users'
T_FLUSH_CMD="redis-cli FLUSHALL"
T_RMRF_CMD="rm -rf /home/user/data"

mk_term() { printf '{"tool_name":"run_in_terminal","tool_input":{"command":"%s"}}' "$1"; }

assert_deny "guard: worker push blocked -> deny" \
  "$GUARD" "$(mk_term "$T_PUSH_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: force-flag push blocked even with FF_PUSH -> deny" \
  "$GUARD" "$(mk_term "$T_FPUSH_CMD")" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" "TRACK_ALLOW_FF_PUSH=1"

assert_deny "guard: pr-merge command blocked -> deny" \
  "$GUARD" "$(mk_term "$T_PRMERGE_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_deny "guard: reset-hard command blocked -> deny" \
  "$GUARD" "$(mk_term "$T_RESETHARD_CMD")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_allow "guard: ff-push with TRACK_ALLOW_FF_PUSH=1 -> allow" \
  "$GUARD" "$(mk_term "$T_FFPUSH_CMD")" \
  "TRACK_ALLOWED_PREFIXES=backend-go/" "TRACK_ALLOW_FF_PUSH=1"

assert_deny "guard: DROP TABLE with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_DROP_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

assert_deny "guard: FLUSHALL with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_FLUSH_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

assert_deny "guard: rm-rf absolute path with TRACK_GUARD_DESTRUCTIVE -> deny" \
  "$GUARD" "$(mk_term "$T_RMRF_CMD")" "TRACK_GUARD_DESTRUCTIVE=1"

# Benign commands MUST pass — guards against an over-broad deny regex regression.
assert_allow "guard: benign 'go test' terminal command -> allow" \
  "$GUARD" "$(mk_term "go test ./...")" "TRACK_ALLOWED_PREFIXES=backend-go/"

assert_allow "guard: benign 'git status' terminal command -> allow" \
  "$GUARD" "$(mk_term "git status")" "TRACK_ALLOWED_PREFIXES=backend-go/"

# A tool that is neither a file-edit nor a terminal call falls through untouched.
assert_allow "guard: unrelated tool (read_file) -> allow (no interception)" \
  "$GUARD" '{"tool_name":"read_file","tool_input":{"filePath":"anything.go"}}'

# ---------------------------------------------------------------------------
# SUITE 5 -- track-evidence.sh (producer) + producer->gate contract
# ---------------------------------------------------------------------------
# The CAPTURE half of the evidence gate. Records here are PRODUCED by
# track-evidence.sh (never hand-written), then fed straight into the real gate so
# the producer->consumer contract (field shape + fingerprint parity) is exercised
# end-to-end. If the producer drifts from the gate, these fail — unit-only tests
# that hand-write the record would not.
section "track-evidence.sh (producer)"

PROD_RUNS="$(mktemp -d)"
PROD_RID="prod-$(date +%s)"

# no-op: RUN_ID unset -> nothing recorded
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."}}' \
  | RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" bash "$EVIDENCE" >/dev/null 2>&1 || true
[ -z "$(ls -A "$PROD_RUNS" 2>/dev/null)" ] \
  && pass "evidence(producer): RUN_ID unset -> no record written" \
  || fail "evidence(producer): RUN_ID unset -> no record written"

# no-op: no matcher declared -> nothing recorded
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."}}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" bash "$EVIDENCE" >/dev/null 2>&1 || true
[ ! -f "$PROD_RUNS/$PROD_RID.json" ] \
  && pass "evidence(producer): no matcher set -> no record written" \
  || fail "evidence(producer): no matcher set -> no record written"

# no-op: non-terminal tool is ignored
printf '{"tool_name":"create_file","tool_input":{"filePath":"x.go"}}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
[ ! -f "$PROD_RUNS/$PROD_RID.json" ] \
  && pass "evidence(producer): non-terminal tool -> no record" \
  || fail "evidence(producer): non-terminal tool -> no record"

# TRACK_TEST_CMD_PATTERN match -> recorded with default kind "test"
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test ./..."},"tool_response":"ok  0.5s"}' \
  | RUN_ID="$PROD_RID" RUNS_DIR="$PROD_RUNS" TRACK_TEST_CMD_PATTERN="go test" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
kind_seen=$(jq -r '.evidence[-1].kind // empty' "$PROD_RUNS/$PROD_RID.json" 2>/dev/null)
[ "$kind_seen" = "test" ] \
  && pass "evidence(producer): TEST_CMD_PATTERN match -> kind=test recorded" \
  || fail "evidence(producer): TEST_CMD_PATTERN match -> kind=test (got: $kind_seen)"

# TRACK_EVIDENCE_KINDS label:pattern derivation (first match wins)
PROD_RID2="prod2-$(date +%s)"
printf '{"tool_name":"run_in_terminal","tool_input":{"command":"go test -race ./..."},"tool_response":"ok"}' \
  | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
    TRACK_EVIDENCE_KINDS="go-test:go test -race;py:uv run pytest" \
    bash "$EVIDENCE" >/dev/null 2>&1 || true
kind2=$(jq -r '.evidence[-1].kind // empty' "$PROD_RUNS/$PROD_RID2.json" 2>/dev/null)
[ "$kind2" = "go-test" ] \
  && pass "evidence(producer): EVIDENCE_KINDS label derived (go-test)" \
  || fail "evidence(producer): EVIDENCE_KINDS label derived (got: $kind2)"

# Producer fingerprint MUST equal the current tree fingerprint (== gate's compute)
fp_prod=$(jq -r '.evidence[-1].fingerprint // empty' "$PROD_RUNS/$PROD_RID2.json" 2>/dev/null)
fp_now=$(current_fingerprint)
[ -n "$fp_prod" ] && [ "$fp_prod" = "$fp_now" ] \
  && pass "evidence(producer): fingerprint == current tree (producer<->gate parity)" \
  || fail "evidence(producer): fingerprint mismatch (producer=$fp_prod now=$fp_now)"

# END-TO-END: a producer-captured pass at the current FP satisfies the real gate
result=$(printf '{"stop_hook_active":false}' | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
         TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
[ -z "$result" ] \
  && pass "evidence(e2e): producer pass at current FP -> gate allows" \
  || fail "evidence(e2e): producer pass -> gate allows (got: $result)"

# END-TO-END: a second required kind with no producer entry -> gate blocks, names it
result=$(printf '{"stop_hook_active":false}' | RUN_ID="$PROD_RID2" RUNS_DIR="$PROD_RUNS" \
         TRACK_REQUIRED_EVIDENCE="go-test,py" bash "$EVIDENCE_GATE" 2>&1) || true
if printf '%s' "$result" | grep -qiE '"block"|MISSING' && printf '%s' "$result" | grep -q 'py'; then
  pass "evidence(e2e): multi-kind, one kind missing -> gate blocks (names py)"
else fail "evidence(e2e): multi-kind missing -> gate blocks (got: $result)"; fi

rm -rf "$PROD_RUNS"

# ---------------------------------------------------------------------------
# SUITE 6 -- track-evidence-gate.sh
# ---------------------------------------------------------------------------
section "track-evidence-gate.sh"

if [ -n "$RUN1_ID" ]; then
  EMPTY_REC="$(mktemp -d)"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$EMPTY_REC" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  rm -rf "$EMPTY_REC"
  printf '%s' "$result" | grep -q '"block"' \
    && pass "evidence-gate: missing run record -> block" \
    || fail "evidence-gate: missing run record -> block"

  result=$(printf '{"stop_hook_active":true}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: stop_hook_active -> no-op" \
    || fail "evidence-gate: stop_hook_active -> no-op"

  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: no required evidence -> no-op" \
    || fail "evidence-gate: no required evidence -> no-op"

  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  [ -z "$result" ] && pass "evidence-gate: fresh evidence at current FP -> allow" \
    || fail "evidence-gate: fresh evidence at current FP -> allow (got: $result)"

  jq -nc '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":"0000000000000000000000000000000000000001"}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  printf '%s' "$result" | grep -qiE '"block"|STALE' \
    && pass "evidence-gate: stale FP -> block" || fail "evidence-gate: stale FP -> block"

  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"--- FAIL: TestX\nFAIL\texit code 1","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test" bash "$EVIDENCE_GATE" 2>&1) || true
  printf '%s' "$result" | grep -qiE '"block"|FAILING' \
    && pass "evidence-gate: FAIL marker -> block" || fail "evidence-gate: FAIL marker -> block"

  # Multi-kind: one kind fresh+passing, a second REQUIRED kind absent -> block naming it.
  FP=$(current_fingerprint)
  jq -nc --arg fp "$FP" \
    '{"evidence":[{"kind":"go-test","cmd":"go test","response":"ok","fingerprint":$fp}]}' \
    > "$TMPDIR_RUNS/$RUN1_ID.json"
  result=$(printf '{"stop_hook_active":false}' | RUN_ID="$RUN1_ID" RUNS_DIR="$TMPDIR_RUNS" \
           TRACK_REQUIRED_EVIDENCE="go-test,py" bash "$EVIDENCE_GATE" 2>&1) || true
  if printf '%s' "$result" | grep -qiE '"block"|MISSING' && printf '%s' "$result" | grep -q 'py'; then
    pass "evidence-gate: multi-kind, second kind missing -> block names it"
  else fail "evidence-gate: multi-kind missing -> block (got: $result)"; fi
else
  for i in 1 2 3 4 5 6 7; do skip "evidence-gate: skipped (no RUN1_ID)"; done
fi

# ---------------------------------------------------------------------------
# SUITE 7 -- track-sentinel.sh
# ---------------------------------------------------------------------------
section "track-sentinel.sh"

result=$(printf '{"stop_hook_active":true}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
[ -z "$result" ] && pass "sentinel: stop_hook_active -> no-op" \
  || fail "sentinel: stop_hook_active -> no-op"

result=$(printf '{"stop_hook_active":false}' | bash "$SENTINEL" 2>&1) || true
[ -z "$result" ] && pass "sentinel: TRACK_SENTINEL unset -> no-op" \
  || fail "sentinel: TRACK_SENTINEL unset -> no-op"

TMP_SECRET="sbd_tst_secret_$$.py"
# Deliberately split so push-protection scanners never see a valid key pattern.
# The sentinel checks for 'sk_' + 'live_' as separate regex components.
printf 'API_KEY = "sk_''live_''TEST_SENTINEL_FIXTURE_NOT_A_SECRET"\n' > "$TMP_SECRET"
git add "$TMP_SECRET"
SCRATCH_FILES+=("$TMP_SECRET")
result=$(printf '{"stop_hook_active":false}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
git rm --cached "$TMP_SECRET" --quiet 2>/dev/null || true; rm -f "$TMP_SECRET"
printf '%s' "$result" | grep -q '"block"' \
  && pass "sentinel: staged secret -> block" || fail "sentinel: staged secret -> block"

TMP_DEBUG="sbd_tst_debug_$$.ts"
printf 'export function foo() {\n  console.log("debug:", x);\n}\n' > "$TMP_DEBUG"
git add "$TMP_DEBUG"
SCRATCH_FILES+=("$TMP_DEBUG")
result=$(printf '{"stop_hook_active":false}' | TRACK_SENTINEL=1 bash "$SENTINEL" 2>&1) || true
git rm --cached "$TMP_DEBUG" --quiet 2>/dev/null || true; rm -f "$TMP_DEBUG"
printf '%s' "$result" | grep -q '"block"' \
  && pass "sentinel: console.log leftover -> block" || fail "sentinel: console.log leftover -> block"

# ---------------------------------------------------------------------------
# SUITE 8 -- track-meter.sh
# ---------------------------------------------------------------------------
section "track-meter.sh"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" TRACK_MAX_TOOL_CALLS=100 \
         bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && fail "meter: under ceiling -> allow" || pass "meter: under ceiling -> allow"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" TRACK_MAX_TOOL_CALLS=0 \
         bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && pass "meter: ceiling=0 -> block" || fail "meter: ceiling=0 -> block"

result=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
         RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$METER" 2>&1) || true
printf '%s' "$result" | grep -qF '"continue":false' \
  && fail "meter: unset ceiling -> no-op" || pass "meter: unset ceiling -> no-op"

# Accumulation + terminal state: three calls against a ceiling of 2 — the count
# must persist across calls, trip on the call that pushes it past the ceiling, and
# stamp status=no-progress for the orchestrator summary.
ACC_RUNS="$(mktemp -d)"; ACC_RID="meter-acc"
out=""
for _ in 1 2 3; do
  out=$(jq -nc '{"tool_name":"create_file","tool_response":"ok"}' | \
        RUN_ID="$ACC_RID" RUNS_DIR="$ACC_RUNS" TRACK_MAX_TOOL_CALLS=2 bash "$METER" 2>&1) || true
done
printf '%s' "$out" | grep -qF '"continue":false' \
  && pass "meter: count accumulates across calls, trips past ceiling" \
  || fail "meter: count accumulates across calls, trips past ceiling (got: $out)"
status_seen=$(jq -r '.status // empty' "$ACC_RUNS/$ACC_RID.json" 2>/dev/null)
[ "$status_seen" = "no-progress" ] \
  && pass "meter: ceiling trip records status=no-progress" \
  || fail "meter: ceiling trip records status=no-progress (got: $status_seen)"
rm -rf "$ACC_RUNS"

# ---------------------------------------------------------------------------
# SUITE 9 -- track-trace.sh
# ---------------------------------------------------------------------------
section "track-trace.sh"

jq -nc '{"run_id":"'"${RUN1_ID:-test}"'","v":1,"trace":[],"evidence":[],"tool_calls":0}' \
  > "$TMPDIR_RUNS/${RUN1_ID:-test}.json"
jq -nc '{"hook_event_name":"SubagentStart","agent_id":"a001","agent_type":"impl"}' | \
  RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$TRACE" >/dev/null 2>&1 || true
trace_len=$(jq '.trace | length' "$TMPDIR_RUNS/${RUN1_ID:-test}.json" 2>/dev/null || echo 0)
[ "$trace_len" -ge 1 ] && pass "trace: SubagentStart -> appended to run record" \
  || fail "trace: SubagentStart -> appended to run record"

result=$(jq -nc '{"hook_event_name":"SubagentStart"}' | bash "$TRACE" 2>&1) || true
[ -z "$result" ] && pass "trace: no RUN_ID -> no-op" || fail "trace: no RUN_ID -> no-op"

# ---------------------------------------------------------------------------
# SUITE 10 -- track-notify.sh
# ---------------------------------------------------------------------------
# Best-effort, fire-and-forget: with no webhook configured it must stay a silent
# no-op and NEVER emit a blocking decision (it runs on Stop after the gate).
section "track-notify.sh"

result=$(printf '{}' | RUN_ID="${RUN1_ID:-test}" RUNS_DIR="$TMPDIR_RUNS" bash "$NOTIFY" 2>&1) || true
[ -z "$result" ] \
  && pass "notify: no webhook -> silent no-op (never blocks)" \
  || fail "notify: no webhook -> silent no-op (got: $result)"

# ---------------------------------------------------------------------------
# SUITE 11 -- SKILL.md + track-hooks.json structural integrity
# ---------------------------------------------------------------------------
section "SKILL.md + hooks structural integrity"

SKILL_MD="$SCRIPT_DIR/../SKILL.md"
HOOKS_JSON="$SCRIPT_DIR/../templates/track-hooks.json"

# 10.1 — all expected scripts exist
EXPECTED_SCRIPTS=(
  track-guard.sh track-preflight.sh track-reconcile.sh
  track-evidence.sh track-evidence-gate.sh
  track-meter.sh track-trace.sh track-sentinel.sh track-notify.sh
)
_all_exist=1
for _s in "${EXPECTED_SCRIPTS[@]}"; do
  [ -f "$SCRIPTS_DIR/$_s" ] || { _all_exist=0; break; }
done
[ "$_all_exist" -eq 1 ] \
  && pass "struct: all bundled scripts exist in scripts/" \
  || fail "struct: all bundled scripts exist in scripts/"

# 10.2 — track-hooks.json is valid JSON
jq empty "$HOOKS_JSON" 2>/dev/null \
  && pass "struct: track-hooks.json is valid JSON" \
  || fail "struct: track-hooks.json is valid JSON"

# 10.3 — preToolUse wires track-guard.sh
jq -e '[.hooks.preToolUse[]?.bash] | map(test("track-guard")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: preToolUse -> track-guard.sh" \
  || fail "struct: preToolUse -> track-guard.sh"

# 10.4 — sessionStart wires track-reconcile.sh
jq -e '[.hooks.sessionStart[]?.bash] | map(test("track-reconcile")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: sessionStart -> track-reconcile.sh" \
  || fail "struct: sessionStart -> track-reconcile.sh"

# 10.5 — postToolUse wires both track-evidence.sh and track-meter.sh
jq -e '[.hooks.postToolUse[]?.bash] | map(test("track-evidence[^-]|track-evidence\\.")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: postToolUse -> track-evidence.sh" \
  || fail "struct: postToolUse -> track-evidence.sh"
jq -e '[.hooks.postToolUse[]?.bash] | map(test("track-meter")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: postToolUse -> track-meter.sh" \
  || fail "struct: postToolUse -> track-meter.sh"

# 10.6 — stop wires evidence-gate AND sentinel
jq -e '[.hooks.stop[]?.bash] | map(test("track-evidence-gate")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: stop -> track-evidence-gate.sh" \
  || fail "struct: stop -> track-evidence-gate.sh"
jq -e '[.hooks.stop[]?.bash] | map(test("track-sentinel")) | any' \
    "$HOOKS_JSON" >/dev/null 2>&1 \
  && pass "struct: stop -> track-sentinel.sh" \
  || fail "struct: stop -> track-sentinel.sh"

# 10.7 — evidence-gate fires before sentinel in stop array (order matters)
_gate_idx=$(jq '[.hooks.stop[]?.bash] | to_entries
  | map(select(.value | test("track-evidence-gate"))) | .[0].key // 99' \
  "$HOOKS_JSON" 2>/dev/null)
_sentinel_idx=$(jq '[.hooks.stop[]?.bash] | to_entries
  | map(select(.value | test("track-sentinel"))) | .[0].key // 99' \
  "$HOOKS_JSON" 2>/dev/null)
[ "${_gate_idx:-99}" -lt "${_sentinel_idx:-99}" ] 2>/dev/null \
  && pass "struct: stop order — evidence-gate before sentinel" \
  || fail "struct: stop order — evidence-gate before sentinel (gate=${_gate_idx} sentinel=${_sentinel_idx})"

# 10.8 — SKILL.md defines all 8 pipeline steps in order (by first-occurrence line number)
_STEPS=("1\." "2\." "3\." "4\." "5\." "6\." "7\." "8\.")
_steps_ok=1; _prev=0
for _step in "${_STEPS[@]}"; do
  _ln=$(grep -n "^\s*${_step}" "$SKILL_MD" 2>/dev/null | head -1 | cut -d: -f1)
  if [ -z "$_ln" ] || [ "$_ln" -le "$_prev" ] 2>/dev/null; then _steps_ok=0; break; fi
  _prev=$_ln
done
[ "$_steps_ok" -eq 1 ] \
  && pass "struct: SKILL.md defines Steps 1-8 in correct order" \
  || fail "struct: SKILL.md defines Steps 1-8 in correct order"

# 10.9 — Skill-per-step map references all required superpower skills
_REQUIRED_SKILLS=(
  "using-git-worktrees"
  "dispatching-parallel-agents"
  "requesting-code-review"
  "subagent-driven-development"
  "verification-before-completion"
)
_skills_ok=1
for _sk in "${_REQUIRED_SKILLS[@]}"; do
  grep -q "$_sk" "$SKILL_MD" 2>/dev/null || { _skills_ok=0; break; }
done
[ "$_skills_ok" -eq 1 ] \
  && pass "struct: SKILL.md references all required superpower skills" \
  || fail "struct: SKILL.md references all required superpower skills"

# 10.10 — Every script named in track-hooks.json exists in scripts/
_missing=0
while IFS= read -r _scr; do
  [ -z "$_scr" ] && continue
  [ -f "$SCRIPTS_DIR/$_scr" ] || _missing=$((_missing+1))
done < <(jq -r '.. | strings | select(test("track-")) | gsub(".*/"; "")' "$HOOKS_JSON" 2>/dev/null | sort -u)
[ "$_missing" -eq 0 ] \
  && pass "struct: all scripts in track-hooks.json exist in scripts/" \
  || fail "struct: $_missing scripts in track-hooks.json missing from scripts/"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
TOTAL=$((PASS + FAIL + SKIP))
printf '\n===============================================\n'
printf '  single-branch-development  test suite\n'
printf '  Date:   %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
printf '  Branch: %s\n' "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
printf '  Total: %d   passed: %d   failed: %d   skipped: %d\n' \
  "$TOTAL" "$PASS" "$FAIL" "$SKIP"
printf '===============================================\n'
if [ "$FAIL" -gt 0 ]; then
  printf '\nFailed:\n%b\n' "$FAILURES"
  exit 1
fi
exit 0
